'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'bn'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.programs': 'Programs',
    'nav.certifications': 'Certifications',
    'nav.about': 'About',
    'nav.team': 'Team',
    'nav.facilities': 'Facilities',
    'nav.contact': 'Contact',
    'nav.videos': 'Videos',
    'nav.testimonials': 'Testimonials',
    'nav.faq': 'FAQ',
    'nav.process': 'Path to Success',
    'nav.callNow': 'Call Now',
    'nav.basicWelding': 'Basic Welding',
    'nav.advancedMigTig': 'Advanced MIG/TIG',
    'nav.pipeWelding': 'Pipe Welding',
    'nav.underwaterWelding': 'Underwater Welding',
    'nav.roboticWelding': 'Robotic Welding',
    'nav.fabricationDesign': 'Fabrication & Design',

    // Hero
    'hero.banglaTtitle': 'Start Your Welding Career',
    'hero.title1': 'Master the Art of',
    'hero.title2': 'Professional Welding',
    'hero.description': 'Join Bangladesh\'s premier welding training institute. Get internationally recognized certifications and secure high-paying jobs in Europe, Japan, and the Middle East.',
    'hero.startJourney': 'Start Your Journey',
    'hero.watchVideo': 'Watch Video',
    'hero.studentsEnrolled': 'Students Enrolled',
    'hero.jobPlacement': 'Job Placement',
    'hero.certificationRate': 'Certification Rate',
    'hero.quote': '"Skill abroad brings both money and honor"',

    // About
    'about.badge': 'About Us',
    'about.title': 'Building Futures Through',
    'about.titleHighlight': 'Excellence',
    'about.subtitle': 'Since 2010, we have been transforming lives through comprehensive welding education, producing skilled professionals who excel in industries worldwide.',
    'about.content.heading': 'Empowering Dreams Through Skill Development',
    'about.content.paragraph1': 'At New Life Welding Training Center, we believe in the power of skilled hands to transform lives. Our world-class training programs combine traditional techniques with cutting-edge technology.',
    'about.content.paragraph2': 'With over a decade of experience, we have helped thousands of students achieve their dreams of working in prestigious companies across the globe.',
    'about.content.tag1': 'Certified Programs',
    'about.content.tag2': 'Expert Instructors',
    'about.values.heading': 'Our Core',
    'about.values.headingHighlight': 'Values',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.description': 'We pursue the highest standards in welding education and training.',
    'about.values.community.title': 'Community',
    'about.values.community.description': 'Building a supportive network of skilled professionals.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'Embracing new technologies and methods to stay ahead.',
    'about.values.safety.title': 'Safety First',
    'about.values.safety.description': 'Prioritizing safety in every aspect of training.',
    'about.journey.heading': 'Our Journey',
    'about.journey.headingHighlight': 'Milestones',
    'about.quote.badge': 'From Our Chairman',
    'about.quote.title': 'Dream Big, Become Skilled, Conquer the World!',
    'about.quote.text': 'Many dream of building a new and better life abroad. At \'New Life Welding Training Center\', we don\'t just pave the path to that dream — we equip you with the key to success: internationally recognized skills. A skilled worker is the backbone of every nation\'s economy. We don\'t merely teach welding — we ignite the confidence to excel in the global job market. This training isn\'t just a job opportunity; it\'s a gateway to a secure and prosperous future for your family. Remember, it\'s not just hard work — the right skill is the true measure of success!',
    'about.quote.name': 'Abdur Rahman Jony',
    'about.quote.role': 'Chairman, New Life Welding Training Center',
    'about.quote.designation': 'Chairman',
    'about.quote.company': 'New Life Welding Training Center',
    'about.milestones.founded.title': 'Founded',
    'about.milestones.founded.description': 'Started our journey with a vision to transform lives.',
    'about.milestones.expansion.title': 'Expansion',
    'about.milestones.expansion.description': 'Expanded facilities and programs significantly.',
    'about.milestones.recognition.title': 'Recognition',
    'about.milestones.recognition.description': 'Received national recognition for excellence.',
    'about.milestones.innovation.title': 'Innovation',
    'about.milestones.innovation.description': 'Introduced advanced training technologies.',

    // Programs
    'programs.badge': 'Training Programs',
    'programs.title': 'Comprehensive',
    'programs.titleHighlight': 'Welding Programs',
    'programs.subtitle': 'From beginner to expert, find the perfect program to launch or advance your welding career',
    'programs.duration': 'Duration',
    'programs.price': 'Price',
    'programs.learnMore': 'Learn More',
    'programs.viewDetails': 'View Details',

    // Process
    'process.badge': 'Step-by-Step Process',
    'process.title': 'Your Path to',
    'process.titleHighlight': 'Success',
    'process.subtitle': 'A structured, comprehensive approach that takes you from beginner to certified professional',
    'process.duration': 'Duration',
    'process.steps.consultation.title': 'Consultation & Assessment',
    'process.steps.consultation.description': 'Schedule a free consultation to discuss your goals, experience level, and career aspirations.',
    'process.steps.consultation.duration': '1-2 Days',
    'process.steps.consultation.details.0': 'Free career counseling',
    'process.steps.consultation.details.1': 'Skills assessment test',
    'process.steps.consultation.details.2': 'Program recommendation',
    'process.steps.consultation.details.3': 'Financial aid guidance',
    'process.steps.enrollment.title': 'Enrollment & Setup',
    'process.steps.enrollment.description': 'Complete registration, receive your starter kit, and prepare for your welding journey.',
    'process.steps.enrollment.duration': '1-3 Days',
    'process.steps.enrollment.details.0': 'Complete registration',
    'process.steps.enrollment.details.1': 'Receive starter kit',
    'process.steps.enrollment.details.2': 'Safety orientation',
    'process.steps.enrollment.details.3': 'Equipment familiarization',
    'process.steps.foundational.title': 'Foundational Learning',
    'process.steps.foundational.description': 'Master safety protocols, equipment handling, and fundamental welding theory.',
    'process.steps.foundational.duration': '2-4 Weeks',
    'process.steps.foundational.details.0': 'Safety protocols',
    'process.steps.foundational.details.1': 'Equipment handling',
    'process.steps.foundational.details.2': 'Welding theory',
    'process.steps.foundational.details.3': 'Material science',
    'process.steps.practice.title': 'Hands-On Practice',
    'process.steps.practice.description': 'Apply your knowledge with supervised practice sessions on real projects.',
    'process.steps.practice.duration': '4-8 Weeks',
    'process.steps.practice.details.0': 'Supervised practice',
    'process.steps.practice.details.1': 'Real project work',
    'process.steps.practice.details.2': 'Technique refinement',
    'process.steps.practice.details.3': 'Quality control',
    'process.steps.certification.title': 'Certification Testing',
    'process.steps.certification.description': 'Demonstrate your skills through comprehensive practical and written examinations.',
    'process.steps.certification.duration': '1-2 Weeks',
    'process.steps.certification.details.0': 'Written examination',
    'process.steps.certification.details.1': 'Practical test',
    'process.steps.certification.details.2': 'Skill demonstration',
    'process.steps.certification.details.3': 'Certificate issuance',
    'process.steps.career.title': 'Career Placement',
    'process.steps.career.description': 'Leverage our industry connections for job placement and career advancement.',
    'process.steps.career.duration': 'Ongoing',
    'process.steps.career.details.0': 'Job matching',
    'process.steps.career.details.1': 'Interview preparation',
    'process.steps.career.details.2': 'Visa assistance',
    'process.steps.career.details.3': 'Career support',

    // Testimonials
    'testimonials.badge': 'Success Stories',
    'testimonials.title': 'Hear From Our',
    'testimonials.titleHighlight': 'Graduates',
    'testimonials.subtitle': 'Real stories from real students who transformed their lives through welding',

    // Team
    'team.badge': 'Expert Instructors',
    'team.title': 'Meet Our',
    'team.titleHighlight': 'Team',
    'team.subtitle': 'The passionate professionals behind Bangladesh\'s premier welding training institution',

    // Facilities
    'facilities.badge': 'World-Class Facilities',
    'facilities.title': 'Our Training',
    'facilities.titleHighlight': 'Facilities',
    'facilities.subtitle': 'State-of-the-art training environment with professional-grade equipment designed for optimal learning',
    'facilities.items.trainingBays.title': 'Training Bays',
    'facilities.items.trainingBays.description': 'Spacious welding bays equipped with professional workstations for hands-on practice.',
    'facilities.items.trainingBays.specs.0': '40+ Individual Workstations',
    'facilities.items.trainingBays.specs.1': 'Professional Ventilation',
    'facilities.items.trainingBays.specs.2': 'Safety Equipment',
    'facilities.items.trainingBays.specs.3': '24/7 Supervision',
    'facilities.items.classroomLabs.title': 'Classroom Labs',
    'facilities.items.classroomLabs.description': 'Modern classrooms with multimedia facilities for theoretical learning.',
    'facilities.items.classroomLabs.specs.0': 'Smart Boards',
    'facilities.items.classroomLabs.specs.1': 'AC Rooms',
    'facilities.items.classroomLabs.specs.2': 'Video Tutorials',
    'facilities.items.classroomLabs.specs.3': 'Interactive Sessions',
    'facilities.items.safetyCenter.title': 'Safety Center',
    'facilities.items.safetyCenter.description': 'Dedicated area for safety training and emergency preparedness.',
    'facilities.items.safetyCenter.specs.0': 'First Aid Training',
    'facilities.items.safetyCenter.specs.1': 'Fire Safety',
    'facilities.items.safetyCenter.specs.2': 'PPE Training',
    'facilities.items.safetyCenter.specs.3': 'Emergency Protocols',
    'facilities.items.fabricationShop.title': 'Fabrication Shop',
    'facilities.items.fabricationShop.description': 'Complete fabrication facility for advanced project work.',
    'facilities.items.fabricationShop.specs.0': 'CNC Machines',
    'facilities.items.fabricationShop.specs.1': 'Plasma Cutters',
    'facilities.items.fabricationShop.specs.2': 'Metal Benders',
    'facilities.items.fabricationShop.specs.3': 'Quality Tools',
    'facilities.items.studentLounge.title': 'Student Lounge',
    'facilities.items.studentLounge.description': 'Comfortable space for students to relax and network.',
    'facilities.items.studentLounge.specs.0': 'Rest Area',
    'facilities.items.studentLounge.specs.1': 'Cafeteria',
    'facilities.items.studentLounge.specs.2': 'Study Zone',
    'facilities.items.studentLounge.specs.3': 'WiFi Access',
    'facilities.items.testingCenter.title': 'Testing Center',
    'facilities.items.testingCenter.description': 'Certified examination center for all major welding certifications.',
    'facilities.items.testingCenter.specs.0': 'AWS Certified',
    'facilities.items.testingCenter.specs.1': 'Practical Labs',
    'facilities.items.testingCenter.specs.2': 'Written Exams',
    'facilities.items.testingCenter.specs.3': 'Result Processing',

    // FAQ
    'faq.badge': 'FAQ',
    'faq.title': 'Common',
    'faq.titleHighlight': 'Questions',
    'faq.subtitle': 'Everything you need to know about our welding programs',

    // Contact
    'contact.badge': 'Get In Touch',
    'contact.title': 'Contact',
    'contact.titleHighlight': 'Us',
    'contact.description': 'Ready to start your welding career? Reach out to us today!',
    'contact.name': 'Your Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.address': 'Address',
    'contact.callUs': 'Call Us',
    'contact.emailUs': 'Email Us',

    // Footer
    'footer.programs': 'Programs',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.ourTeam': 'Our Team',
    'footer.successStories': 'Success Stories',
    'footer.visaProcessing': 'Visa Processing',
    'footer.rights': 'All rights reserved.',
    'footer.madeWith': 'Made with',
    'footer.inBangladesh': 'in Bangladesh',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',

    // Videos
    'videos.badge': 'Video Gallery',
    'videos.title': 'Watch Our',
    'videos.titleHighlight': 'Training Videos',
    'videos.subtitle': 'See our world-class training facilities and student success stories in action',
  },
  bn: {
    // Navbar
    'nav.home': 'হোম',
    'nav.programs': 'প্রোগ্রাম',
    'nav.certifications': 'সার্টিফিকেশন',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.team': 'টিম',
    'nav.facilities': 'সুবিধাসমূহ',
    'nav.contact': 'যোগাযোগ',
    'nav.videos': 'ভিডিও',
    'nav.testimonials': 'স্নাতকদের কথা',
    'nav.faq': 'প্রশ্নোত্তর',
    'nav.process': 'সাফল্যের পথ',
    'nav.callNow': 'কল করুন',
    'nav.basicWelding': 'বেসিক ওয়েল্ডিং',
    'nav.advancedMigTig': 'অ্যাডভান্সড MIG/TIG',
    'nav.pipeWelding': 'পাইপ ওয়েল্ডিং',
    'nav.underwaterWelding': 'আন্ডারওয়াটার ওয়েল্ডিং',
    'nav.roboticWelding': 'রোবোটিক ওয়েল্ডিং',
    'nav.fabricationDesign': 'ফ্যাব্রিকেশন ও ডিজাইন',

    // Hero
    'hero.banglaTtitle': 'আপনার ওয়েল্ডিং ক্যারিয়ার শুরু করুন',
    'hero.title1': 'পেশাদার ওয়েল্ডিং এর',
    'hero.title2': 'শিল্প আয়ত্ত করুন',
    'hero.description': 'বাংলাদেশের সেরা ওয়েল্ডিং প্রশিক্ষণ প্রতিষ্ঠানে যোগ দিন। আন্তর্জাতিকভাবে স্বীকৃত সার্টিফিকেট অর্জন করুন এবং ইউরোপ, জাপান ও মধ্যপ্রাচ্যে উচ্চ বেতনের চাকরি নিশ্চিত করুন।',
    'hero.startJourney': 'যাত্রা শুরু করুন',
    'hero.watchVideo': 'ভিডিও দেখুন',
    'hero.studentsEnrolled': 'ভর্তি শিক্ষার্থী',
    'hero.jobPlacement': 'চাকরি নিয়োগ',
    'hero.certificationRate': 'সার্টিফিকেশন হার',
    'hero.quote': '"দক্ষ হয়ে বিদেশ গেলে অর্থ সম্মান দুই-ই মেলে"',

    // About
    'about.badge': 'আমাদের সম্পর্কে',
    'about.title': 'উৎকর্ষতার মাধ্যমে',
    'about.titleHighlight': 'ভবিষ্যৎ গড়া',
    'about.subtitle': '২০১০ সাল থেকে, আমরা ব্যাপক ওয়েল্ডিং শিক্ষার মাধ্যমে জীবন পরিবর্তন করছি, দক্ষ পেশাদার তৈরি করছি যারা বিশ্বব্যাপী শিল্পে শ্রেষ্ঠত্ব অর্জন করে।',
    'about.content.heading': 'দক্ষতা উন্নয়নের মাধ্যমে স্বপ্ন পূরণ',
    'about.content.paragraph1': 'নিউ লাইফ ওয়েল্ডিং ট্রেনিং সেন্টারে, আমরা বিশ্বাস করি দক্ষ হাতের শক্তি জীবন বদলাতে পারে। আমাদের বিশ্বমানের প্রশিক্ষণ প্রোগ্রাম ঐতিহ্যবাহী কৌশল এবং অত্যাধুনিক প্রযুক্তির সমন্বয়।',
    'about.content.paragraph2': 'এক দশকেরও বেশি অভিজ্ঞতা নিয়ে, আমরা হাজার হাজার শিক্ষার্থীকে বিশ্বব্যাপী মর্যাদাপূর্ণ কোম্পানিতে কাজ করার স্বপ্ন পূরণে সহায়তা করেছি।',
    'about.content.tag1': 'সার্টিফাইড প্রোগ্রাম',
    'about.content.tag2': 'বিশেষজ্ঞ প্রশিক্ষক',
    'about.values.heading': 'আমাদের মূল',
    'about.values.headingHighlight': 'মূল্যবোধ',
    'about.values.excellence.title': 'উৎকর্ষতা',
    'about.values.excellence.description': 'ওয়েল্ডিং শিক্ষা এবং প্রশিক্ষণে সর্বোচ্চ মান অনুসরণ করা।',
    'about.values.community.title': 'সম্প্রদায়',
    'about.values.community.description': 'দক্ষ পেশাদারদের একটি সহায়ক নেটওয়ার্ক তৈরি করা।',
    'about.values.innovation.title': 'উদ্ভাবন',
    'about.values.innovation.description': 'শিল্পে এগিয়ে থাকতে নতুন প্রযুক্তি এবং পদ্ধতি গ্রহণ করা।',
    'about.values.safety.title': 'নিরাপত্তা প্রথম',
    'about.values.safety.description': 'প্রশিক্ষণের প্রতিটি দিকে নিরাপত্তাকে অগ্রাধিকার দেওয়া।',
    'about.journey.heading': 'আমাদের যাত্রা',
    'about.journey.headingHighlight': 'মাইলস্টোন',
    'about.quote.badge': 'চেয়ারম্যান স্যারের বার্তা',
    'about.quote.title': 'স্বপ্ন দেখুন, দক্ষ হোন, বিশ্ব জয় করুন!',
    'about.quote.text': 'বিদেশের মাটিতে একটি নতুন এবং উন্নত জীবন গড়ার স্বপ্ন দেখেন অনেকেই। আমাদের \'নিউ লাইফ ওয়েল্ডিং ট্রেনিং সেন্টার\'-এ আমরা শুধু সেই স্বপ্নকে সফল করার পথই তৈরি করি না, বরং আমরা আপনাদের হাতে তুলে দিই সেই কঠিন পরিশ্রমের চাবিকাঠি – যা হলো আন্তর্জাতিক মানসম্পন্ন দক্ষতা। আমি বিশ্বাস করি, একজন দক্ষ শ্রমিক যেকোনো দেশের অর্থনীতির জন্য মেরুদণ্ডস্বরূপ। আমরা কেবল ওয়েল্ডিংই শেখাই না, বরং আন্তর্জাতিক চাকরির বাজারে নিজেদের প্রতিষ্ঠিত করার মতো আত্মবিশ্বাস তৈরি করি। এই প্রশিক্ষণ শুধুমাত্র একটি চাকরির সুযোগ নয়; এটি আপনার এবং আপনার পরিবারের জন্য একটি নিরাপদ ও সমৃদ্ধ ভবিষ্যতের প্রবেশদ্বার। মনে রাখবেন, শুধুমাত্র কঠোর পরিশ্রম নয়, সঠিক সময়ে সঠিক দক্ষতা অর্জনই হলো সফলতার মূল চাবিকাঠি!',
    'about.quote.name': '— মো: আব্দুর রহমান জনি',
    'about.quote.role': 'চেয়ারম্যান, নিউ লাইফ ওয়েল্ডিং ট্রেনিং সেন্টার',
    'about.quote.designation': 'চেয়ারম্যান',
    'about.quote.company': 'নিউ লাইফ ওয়েল্ডিং ট্রেনিং সেন্টার',
    'about.milestones.founded.title': 'প্রতিষ্ঠা',
    'about.milestones.founded.description': 'জীবন বদলানোর দৃষ্টিভঙ্গি নিয়ে আমাদের যাত্রা শুরু।',
    'about.milestones.expansion.title': 'সম্প্রসারণ',
    'about.milestones.expansion.description': 'সুবিধা এবং প্রোগ্রাম উল্লেখযোগ্যভাবে সম্প্রসারিত।',
    'about.milestones.recognition.title': 'স্বীকৃতি',
    'about.milestones.recognition.description': 'শ্রেষ্ঠত্বের জন্য জাতীয় স্বীকৃতি অর্জন।',
    'about.milestones.innovation.title': 'উদ্ভাবন',
    'about.milestones.innovation.description': 'উন্নত প্রশিক্ষণ প্রযুক্তি চালু করা হয়েছে।',

    // Programs
    'programs.badge': 'প্রশিক্ষণ প্রোগ্রাম',
    'programs.title': 'ব্যাপক',
    'programs.titleHighlight': 'ওয়েল্ডিং প্রোগ্রাম',
    'programs.subtitle': 'শিক্ষানবিশ থেকে বিশেষজ্ঞ, আপনার ওয়েল্ডিং ক্যারিয়ার শুরু বা এগিয়ে নিতে নিখুঁত প্রোগ্রাম খুঁজুন',
    'programs.duration': 'সময়কাল',
    'programs.price': 'মূল্য',
    'programs.learnMore': 'আরও জানুন',
    'programs.viewDetails': 'বিস্তারিত দেখুন',

    // Process
    'process.badge': 'ধাপে ধাপে প্রক্রিয়া',
    'process.title': 'সাফল্যের',
    'process.titleHighlight': 'পথ',
    'process.subtitle': 'একটি কাঠামোগত, ব্যাপক পদ্ধতি যা আপনাকে শিক্ষানবিশ থেকে সার্টিফাইড পেশাদার করে তোলে',
    'process.duration': 'সময়কাল',
    'process.steps.consultation.title': 'পরামর্শ ও মূল্যায়ন',
    'process.steps.consultation.description': 'আপনার লক্ষ্য, অভিজ্ঞতার স্তর এবং ক্যারিয়ার আকাঙ্ক্ষা আলোচনা করতে বিনামূল্যে পরামর্শ নির্ধারণ করুন।',
    'process.steps.consultation.duration': '১-২ দিন',
    'process.steps.consultation.details.0': 'বিনামূল্যে ক্যারিয়ার কাউন্সেলিং',
    'process.steps.consultation.details.1': 'দক্ষতা মূল্যায়ন পরীক্ষা',
    'process.steps.consultation.details.2': 'প্রোগ্রাম সুপারিশ',
    'process.steps.consultation.details.3': 'আর্থিক সহায়তা নির্দেশনা',
    'process.steps.enrollment.title': 'নথিভুক্তি ও সেটআপ',
    'process.steps.enrollment.description': 'নিবন্ধন সম্পূর্ণ করুন, আপনার স্টার্টার কিট পান এবং আপনার ওয়েল্ডিং যাত্রার জন্য প্রস্তুত হন।',
    'process.steps.enrollment.duration': '১-৩ দিন',
    'process.steps.enrollment.details.0': 'নিবন্ধন সম্পূর্ণ করুন',
    'process.steps.enrollment.details.1': 'স্টার্টার কিট পান',
    'process.steps.enrollment.details.2': 'নিরাপত্তা ওরিয়েন্টেশন',
    'process.steps.enrollment.details.3': 'সরঞ্জাম পরিচিতি',
    'process.steps.foundational.title': 'মৌলিক শিক্ষা',
    'process.steps.foundational.description': 'নিরাপত্তা প্রোটোকল, সরঞ্জাম পরিচালনা এবং মৌলিক ওয়েল্ডিং তত্ত্ব আয়ত্ত করুন।',
    'process.steps.foundational.duration': '২-৪ সপ্তাহ',
    'process.steps.foundational.details.0': 'নিরাপত্তা প্রোটোকল',
    'process.steps.foundational.details.1': 'সরঞ্জাম পরিচালনা',
    'process.steps.foundational.details.2': 'ওয়েল্ডিং তত্ত্ব',
    'process.steps.foundational.details.3': 'উপাদান বিজ্ঞান',
    'process.steps.practice.title': 'হাতে-কলমে অনুশীলন',
    'process.steps.practice.description': 'প্রকৃত প্রকল্পে তত্ত্বাবধানে অনুশীলন সেশনের মাধ্যমে আপনার জ্ঞান প্রয়োগ করুন।',
    'process.steps.practice.duration': '৪-৮ সপ্তাহ',
    'process.steps.practice.details.0': 'তত্ত্বাবধানে অনুশীলন',
    'process.steps.practice.details.1': 'বাস্তব প্রকল্পের কাজ',
    'process.steps.practice.details.2': 'কৌশল পরিমার্জন',
    'process.steps.practice.details.3': 'মান নিয়ন্ত্রণ',
    'process.steps.certification.title': 'সার্টিফিকেশন পরীক্ষা',
    'process.steps.certification.description': 'ব্যাপক ব্যবহারিক এবং লিখিত পরীক্ষার মাধ্যমে আপনার দক্ষতা প্রদর্শন করুন।',
    'process.steps.certification.duration': '১-২ সপ্তাহ',
    'process.steps.certification.details.0': 'লিখিত পরীক্ষা',
    'process.steps.certification.details.1': 'ব্যবহারিক পরীক্ষা',
    'process.steps.certification.details.2': 'দক্ষতা প্রদর্শন',
    'process.steps.certification.details.3': 'সার্টিফিকেট প্রদান',
    'process.steps.career.title': 'ক্যারিয়ার নিয়োগ',
    'process.steps.career.description': 'চাকরি নিয়োগ এবং ক্যারিয়ার অগ্রগতির জন্য আমাদের শিল্প সংযোগ ব্যবহার করুন।',
    'process.steps.career.duration': 'চলমান',
    'process.steps.career.details.0': 'চাকরি ম্যাচিং',
    'process.steps.career.details.1': 'ইন্টারভিউ প্রস্তুতি',
    'process.steps.career.details.2': 'ভিসা সহায়তা',
    'process.steps.career.details.3': 'ক্যারিয়ার সাপোর্ট',

    // Testimonials
    'testimonials.badge': 'সাফল্যের গল্প',
    'testimonials.title': 'আমাদের',
    'testimonials.titleHighlight': 'গ্র্যাজুয়েটদের কথা',
    'testimonials.subtitle': 'প্রকৃত শিক্ষার্থীদের প্রকৃত গল্প যারা ওয়েল্ডিংয়ের মাধ্যমে তাদের জীবন পরিবর্তন করেছে',

    // Team
    'team.badge': 'বিশেষজ্ঞ প্রশিক্ষক',
    'team.title': 'আমাদের',
    'team.titleHighlight': 'টিমের সাথে পরিচিত হন',
    'team.subtitle': 'বাংলাদেশের সেরা ওয়েল্ডিং প্রশিক্ষণ প্রতিষ্ঠানের পেছনে উৎসর্গীকৃত পেশাদাররা',

    // Facilities
    'facilities.badge': 'বিশ্বমানের সুবিধা',
    'facilities.title': 'আমাদের প্রশিক্ষণ',
    'facilities.titleHighlight': 'সুবিধাসমূহ',
    'facilities.subtitle': 'সর্বোত্তম শিক্ষার জন্য ডিজাইন করা পেশাদার-গ্রেড সরঞ্জাম সহ অত্যাধুনিক প্রশিক্ষণ পরিবেশ',
    'facilities.items.trainingBays.title': 'প্রশিক্ষণ বে',
    'facilities.items.trainingBays.description': 'হাতে-কলমে অনুশীলনের জন্য পেশাদার ওয়ার্কস্টেশন সজ্জিত প্রশস্ত ওয়েল্ডিং বে।',
    'facilities.items.trainingBays.specs.0': '৪০+ স্বতন্ত্র ওয়ার্কস্টেশন',
    'facilities.items.trainingBays.specs.1': 'পেশাদার বায়ু চলাচল',
    'facilities.items.trainingBays.specs.2': 'নিরাপত্তা সরঞ্জাম',
    'facilities.items.trainingBays.specs.3': '২৪/৭ তত্ত্বাবধান',
    'facilities.items.classroomLabs.title': 'ক্লাসরুম ল্যাব',
    'facilities.items.classroomLabs.description': 'তাত্ত্বিক শিক্ষার জন্য মাল্টিমিডিয়া সুবিধা সহ আধুনিক ক্লাসরুম।',
    'facilities.items.classroomLabs.specs.0': 'স্মার্ট বোর্ড',
    'facilities.items.classroomLabs.specs.1': 'এসি রুম',
    'facilities.items.classroomLabs.specs.2': 'ভিডিও টিউটোরিয়াল',
    'facilities.items.classroomLabs.specs.3': 'ইন্টারঅ্যাক্টিভ সেশন',
    'facilities.items.safetyCenter.title': 'নিরাপত্তা কেন্দ্র',
    'facilities.items.safetyCenter.description': 'নিরাপত্তা প্রশিক্ষণ এবং জরুরি প্রস্তুতির জন্য নিবেদিত এলাকা।',
    'facilities.items.safetyCenter.specs.0': 'প্রাথমিক চিকিৎসা প্রশিক্ষণ',
    'facilities.items.safetyCenter.specs.1': 'অগ্নি নিরাপত্তা',
    'facilities.items.safetyCenter.specs.2': 'পিপিই প্রশিক্ষণ',
    'facilities.items.safetyCenter.specs.3': 'জরুরি প্রোটোকল',
    'facilities.items.fabricationShop.title': 'ফ্যাব্রিকেশন শপ',
    'facilities.items.fabricationShop.description': 'উন্নত প্রকল্পের কাজের জন্য সম্পূর্ণ ফ্যাব্রিকেশন সুবিধা।',
    'facilities.items.fabricationShop.specs.0': 'সিএনসি মেশিন',
    'facilities.items.fabricationShop.specs.1': 'প্লাজমা কাটার',
    'facilities.items.fabricationShop.specs.2': 'মেটাল বেন্ডার',
    'facilities.items.fabricationShop.specs.3': 'মানসম্মত সরঞ্জাম',
    'facilities.items.studentLounge.title': 'স্টুডেন্ট লাউঞ্জ',
    'facilities.items.studentLounge.description': 'শিক্ষার্থীদের বিশ্রাম এবং নেটওয়ার্কিংয়ের জন্য আরামদায়ক স্থান।',
    'facilities.items.studentLounge.specs.0': 'বিশ্রাম এলাকা',
    'facilities.items.studentLounge.specs.1': 'ক্যাফেটেরিয়া',
    'facilities.items.studentLounge.specs.2': 'স্টাডি জোন',
    'facilities.items.studentLounge.specs.3': 'ওয়াইফাই অ্যাক্সেস',
    'facilities.items.testingCenter.title': 'টেস্টিং সেন্টার',
    'facilities.items.testingCenter.description': 'সমস্ত প্রধান ওয়েল্ডিং সার্টিফিকেশনের জন্য সার্টিফাইড পরীক্ষা কেন্দ্র।',
    'facilities.items.testingCenter.specs.0': 'AWS সার্টিফাইড',
    'facilities.items.testingCenter.specs.1': 'ব্যবহারিক ল্যাব',
    'facilities.items.testingCenter.specs.2': 'লিখিত পরীক্ষা',
    'facilities.items.testingCenter.specs.3': 'ফলাফল প্রসেসিং',

    // FAQ
    'faq.badge': 'প্রশ্নোত্তর',
    'faq.title': 'সাধারণ',
    'faq.titleHighlight': 'প্রশ্নসমূহ',
    'faq.subtitle': 'আমাদের ওয়েল্ডিং প্রশিক্ষণ প্রোগ্রাম সম্পর্কে আপনার যা জানা দরকার',

    // Contact
    'contact.badge': 'যোগাযোগ করুন',
    'contact.title': 'আমাদের সাথে',
    'contact.titleHighlight': 'যোগাযোগ',
    'contact.description': 'আপনার ওয়েল্ডিং ক্যারিয়ার শুরু করতে প্রস্তুত? আজই আমাদের সাথে যোগাযোগ করুন!',
    'contact.name': 'আপনার নাম',
    'contact.email': 'ইমেইল ঠিকানা',
    'contact.phone': 'ফোন নম্বর',
    'contact.message': 'আপনার বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'contact.address': 'ঠিকানা',
    'contact.callUs': 'কল করুন',
    'contact.emailUs': 'ইমেইল করুন',

    // Footer
    'footer.programs': 'প্রোগ্রাম',
    'footer.company': 'কোম্পানি',
    'footer.aboutUs': 'আমাদের সম্পর্কে',
    'footer.ourTeam': 'আমাদের টিম',
    'footer.successStories': 'সাফল্যের গল্প',
    'footer.visaProcessing': 'ভিসা প্রসেসিং',
    'footer.rights': 'সর্বস্বত্ব সংরক্ষিত।',
    'footer.madeWith': 'তৈরি করা হয়েছে',
    'footer.inBangladesh': 'বাংলাদেশে',
    'footer.privacyPolicy': 'গোপনীয়তা নীতি',
    'footer.termsOfService': 'সেবার শর্তাবলী',

    // Videos
    'videos.badge': 'ভিডিও গ্যালারি',
    'videos.title': 'আমাদের দেখুন',
    'videos.titleHighlight': 'প্রশিক্ষণ ভিডিও',
    'videos.subtitle': 'আমাদের বিশ্বমানের প্রশিক্ষণ সুবিধা এবং শিক্ষার্থীদের সাফল্যের গল্প দেখুন',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('bn')

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
